apiVersion: 1

datasources:
  - name: "MariaDB-Prod"
    type: mysql
    access: proxy
    isDefault: false
    url: "192.168.0.103:3306"
    database: "healthtracker"
    user: "healthuser"
    jsonData:
      tlsSkipVerify: true
    secureJsonData:
      password: "healthpassword"
